const SUPABASE_URL='https://bnvggkyyomqdnjjvuisi.supabase.co';
const SUPABASE_KEY='sb_publishable_jJR6rexLFY4u9QXHt7fsaQ_9jR_vNHP';
const money=n=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const defaultProducts=[['Alfajor',550,850],['Arrollado carne',700,1100],['Arrollado hawaii',650,1100],['Baguette',1660,3500],['Bizcocho',700,1100],['Boya casera',325,650],['Budin',585,1100],['Cachos',690,950],['Canastita',500,850],['Costillas',220,350],['Dona',600,1000],['Empanada',250,350],['Enchilada maduro',900,1500],['Enchilada papa',650,1100],['Enchilada pinto',750,1200],['Estrella guayaba',700,1200],['Gato',550,950],['Manita natillera',850,1300],['Manita salada',700,1000],['Orejita',450,650],['Palito queso',400,650],['Pan elote',770,1100],['Pan Pizza',700,1100],['Pan yuca',770,1100],['Panuelos',700,1100],['Pizza',700,1000],['Pupusas',700,1150],['Queque beteado',440,850],['Queque seco',440,850],['Quesadilla',550,850],['Roll canela',650,1100],['Volcan coco',650,900],['Trenza Carne',1500,2200],['Trenza Coco pina',1500,2200],['Trenza Jalea',1500,2200],['Trenza Natillera',1300,1950],['Trenza Salada',1000,1850],['Arroz con leche',1000,1500],['Cheesecake',1750,2500],['Churchill',1750,2500],['Flan coco',1200,2000],['Queque chocolate',1375,2000],['Queque higo',1500,1750],['Queque zanahoria',1500,1750],['Torta chilena',1340,2000],['Tres leches',1750,2500]].map((p,i)=>({id:i+1,name:p[0],cost:p[1],price:p[2]}));
let state={user:null,profile:null,products:[],orders:[],finance:[]};
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const userKey=key=>`bdp-${key}-${state.user?.username||'guest'}`;
const legacyMigration=()=>{if(state.user?.username!=='bdlisboa')return;for(const key of ['orders','finance']){const target=userKey(key);if(!localStorage.getItem(target)&&localStorage.getItem(`bdp-${key}`))localStorage.setItem(target,localStorage.getItem(`bdp-${key}`))}};
const saveLocal=()=>{localStorage.setItem(userKey('orders'),JSON.stringify(state.orders));localStorage.setItem(userKey('finance'),JSON.stringify(state.finance))};
async function api(path,options={}){const token=state.user?.access_token;const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(await response.text());return response.status===204?null:response.json()}
async function loadRemote(){try{state.products=(await api('products?select=*&active=eq.true&order=name.asc')||[]).map(p=>({...p,cost:p.purchase_price,price:p.sale_price}));state.finance=await api('financial_entries?select=*&order=entry_date.desc')||[];const orders=await api('orders?select=*,order_items(*)&order=order_date.desc')||[];state.orders=orders.flatMap(o=>(o.order_items||[]).map(i=>{const p=state.products.find(x=>x.id===i.product_id);return {date:o.order_date,product:p?.name||'Producto',qty:i.quantity||0,cost:i.unit_cost||0,total:(i.quantity||0)*(i.unit_cost||0)}}));}catch{state.products=[]}}
function loadLocal(){legacyMigration();state.orders=read(userKey('orders'));state.finance=read(userKey('finance'));state.products=read('bdp-products',defaultProducts)}
function showUser(){const name=state.profile?.display_name||state.user.username;document.getElementById('currentUserLabel').textContent=name;document.getElementById('sidebarUser').textContent=name;document.getElementById('sidebarRole').textContent=state.profile?.role==='admin'?'Administrador':'Sucursal';document.getElementById('avatar').textContent=name.slice(0,1).toUpperCase();document.getElementById('today').textContent=new Date().toLocaleDateString('es-CR',{day:'numeric',month:'short',year:'numeric'})}
const sums=()=>({purchases:state.orders.reduce((a,o)=>a+Number(o.total||0),0),sales:state.finance.filter(x=>(x.entry_type||x.type)==='sale').reduce((a,x)=>a+Number(x.amount||0),0),expenses:state.finance.filter(x=>(x.entry_type||x.type)!=='sale').reduce((a,x)=>a+Number(x.amount||0)});
function render(view='dashboard'){const titles={dashboard:'Resumen general',orders:'Recepcion de pedidos',finance:'Finanzas',catalog:'Catalogo de productos'};document.getElementById('viewTitle').textContent=titles[view];document.getElementById('content').innerHTML=({dashboard,orders,finance,catalog})[view]();if(view==='orders')bindOrders();if(view==='finance')bindFinance();if(view==='catalog')bindCatalog()}
function dashboard(){const x=sums();return `<div class="grid stats"><div class="card"><div class="stat-label">Compras registradas</div><div class="stat-value">${money(x.purchases)}</div></div><div class="card"><div class="stat-label">Ventas registradas</div><div class="stat-value">${money(x.sales)}</div></div><div class="card"><div class="stat-label">Gastos operativos</div><div class="stat-value">${money(x.expenses)}</div></div><div class="card"><div class="stat-label">Resultado estimado</div><div class="stat-value ${x.sales-x.expenses>=0?'positive':'negative'}">${money(x.sales-x.expenses)}</div></div></div><div class="grid two"><div class="card"><div class="card-head"><h3>Pedidos recientes</h3></div>${historyOrders()}</div><div class="card"><h3>Cuenta activa</h3><p class="muted">${state.profile?.display_name||state.user.username}</p><p class="pill">${state.profile?.role==='admin'?'Administrador':'Datos de sucursal'}</p></div></div>`}
function historyOrders(){return state.orders.length?`<div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Producto</th><th>Cantidad</th><th>Total</th></tr>${state.orders.slice().reverse().slice(0,8).map(o=>`<tr><td>${o.date}</td><td>${o.product}</td><td>${o.qty}</td><td>${money(o.total)}</td></tr>`).join('')}</table></div>`:'<div class="empty">No hay pedidos para este usuario.</div>'}
function orders(){const products=state.products;return `<div class="card"><div class="card-head"><div><h3>Nuevo pedido</h3><p class="muted">Indica la cantidad de cada producto.</p></div><span class="pill">Compra</span></div><form id="orderForm"><div class="product-grid">${products.map(p=>`<article class="product-card"><div class="product-name">${p.name}</div><div class="product-price">${money(p.cost)} por unidad</div><label>Cantidad<input class="product-qty" data-id="${p.id}" type="number" min="0" value="0" inputmode="numeric"></label></article>`).join('')||'<div class="empty">No hay productos disponibles.</div>'}</div><div class="order-footer"><label>Fecha<input id="orderDate" type="date" value="${today()}"></label><div class="order-total"><span>Total del pedido</span><strong id="orderTotal">${money(0)}</strong></div><button class="primary">Guardar pedido</button></div></form></div><div class="card" style="margin-top:18px"><div class="card-head"><h3>Historial</h3><span class="muted">${state.orders.length} registros</span></div>${historyOrders()}</div>`}
function bindOrders(){const inputs=[...document.querySelectorAll('.product-qty')];const total=()=>inputs.reduce((a,i)=>{const p=state.products.find(x=>String(x.id)===i.dataset.id);return a+(+i.value||0)*(+p?.cost||0)},0);inputs.forEach(i=>i.oninput=()=>document.getElementById('orderTotal').textContent=money(total()));document.getElementById('orderForm').onsubmit=async e=>{e.preventDefault();const date=document.getElementById('orderDate').value;const rows=inputs.flatMap(i=>{const qty=+i.value||0,p=state.products.find(x=>String(x.id)===i.dataset.id);return qty?[{date,product:p.name,product_id:p.id,qty,cost:p.cost,total:qty*p.cost}]:[]});if(!rows.length)return alert('Selecciona al menos un producto.');try{const order=(await api('orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({branch:state.profile?.branch||null,order_date:date,created_by:state.user.user.id})}))[0];await api('order_items',{method:'POST',body:JSON.stringify(rows.map(r=>({order_id:order.id,product_id:r.product_id,quantity:r.qty,unit_cost:r.cost})))});state.orders.push(...rows);render('orders')}catch(err){alert('No se pudo guardar el pedido en la base de datos.')}}}
function finance(){return `<div class="card"><div class="card-head"><h3>Registrar movimiento</h3></div><form id="financeForm" class="form-grid"><label>Tipo<select id="financeType"><option value="sale">Venta diaria</option><option value="supplier">Pago a proveedor</option><option value="payroll">Pago de planilla</option><option value="other">Otro pago</option></select></label><label>Monto<input id="financeAmount" type="number" min="0" required></label><label>Fecha<input id="financeDate" type="date" value="${today()}"></label><button class="primary">Guardar movimiento</button></form></div><div class="card" style="margin-top:18px"><div class="card-head"><h3>Movimientos</h3></div><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Tipo</th><th>Monto</th></tr>${state.finance.slice().reverse().map(x=>`<tr><td>${x.date||x.entry_date}</td><td>${x.entry_type||x.type}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">Sin movimientos</td></tr>'}</table></div></div>`}
function bindFinance(){document.getElementById('financeForm').onsubmit=async e=>{e.preventDefault();const row={branch:state.profile?.branch||null,entry_type:financeType.value,amount:+financeAmount.value,entry_date:financeDate.value,created_by:state.user.user.id};try{const saved=await api('financial_entries',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});state.finance.unshift(saved?.[0]||row);render('finance')}catch(err){alert('No se pudo guardar el movimiento en la base de datos.')}}}
function catalog(){const admin=state.profile?.role==='admin';return `<div class="card"><div class="card-head"><h3>Productos compartidos</h3>${admin?'<button id="newProduct" class="link">Nuevo producto</button>':'<span class="pill">Solo lectura</span>'}</div><div class="table-wrap"><table class="table"><tr><th>Producto</th><th>Compra</th><th>Venta</th></tr>${state.products.map(p=>`<tr><td>${p.name}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td></tr>`).join('')}</table></div></div>`}
function bindCatalog(){const b=document.getElementById('newProduct');if(b)b.onclick=()=>alert('La administracion de productos se habilitara desde la aplicacion de escritorio.')}
async function login(e){e.preventDefault();const entered=document.getElementById('username').value.trim().toLowerCase(),password=document.getElementById('password').value,error=document.getElementById('loginError');error.textContent='';const email=entered.includes('@')?entered:`${entered}@bakerydreams.com`;try{localStorage.removeItem('bdp-session');localStorage.removeItem('bdp-profile');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error('Usuario o contrasena incorrectos.');state.user={...data,username:entered.includes('@')?entered.split('@')[0]:entered};const rows=await api(`profiles?select=display_name,role,branch&id=eq.${data.user.id}`);state.profile=rows[0]||{display_name:state.user.username,role:'branch',branch:null};localStorage.setItem('bdp-session',JSON.stringify(state.user));localStorage.setItem('bdp-profile',JSON.stringify(state.profile));await loadRemote();if(!state.products.length)loadLocal();document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');showUser();render()}catch(err){state.user=null;error.textContent=err.message.includes('Failed')?'No se pudo conectar con el servidor. Intenta nuevamente.':err.message}}
function logout(){localStorage.removeItem('bdp-session');localStorage.removeItem('bdp-profile');location.reload()}
document.getElementById('loginForm').onsubmit=login;document.getElementById('logout').onclick=logout;document.getElementById('topLogout').onclick=logout;document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.querySelectorAll('.nav-item').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById('sidebar').classList.remove('open');render(button.dataset.view)});
(async()=>{const saved=read('bdp-session',null);if(!saved?.access_token)return;state.user=saved;state.profile=read('bdp-profile',null);await loadRemote();if(!state.products.length)loadLocal();document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');showUser();render()})();

