/* Proformas, recepción y configuración de impresión de BDPedidos. */
(function(){
  const role=()=>state.profile?.role||'';
  const branches=()=>String(state.profile?.branch||'').split(',').map(x=>x.trim()).filter(Boolean);
  const isSupplier=()=>role()==='admin'||role()==='proveedor';
  const isBranch=()=>role()==='branch';
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const moneySafe=value=>money(Number(value)||0);
  const branchLabel=value=>value==='lisboa'?'BD Lisboa':'BD Barrio';
  const selectedBranch=()=>state.business&&state.business!=='all'?state.business:branches()[0]||'lisboa';
  const productById=id=>state.products.find(p=>String(p.id)===String(id));
  async function loadProformas(){try{state.proformas=await api('proforma_invoices?select=*,proforma_items(*)&order=created_at.desc')||[]}catch{state.proformas=[]}}
  const oldLoad=loadRemote;loadRemote=async()=>{await oldLoad();await loadProformas()};
  const statusLabel={pending:'Pendiente',received:'Recibida',partial:'Parcialmente recibida',confirmed:'Confirmada',cancelled:'Cancelada'};
  function proformaRows(items){return (items||[]).map(item=>{const p=productById(item.product_id);return {...item,name:p?.name||'Producto',subtotal:Number(item.quantity||0)*Number(item.unit_price||0)}})}
  function proformaTable(p,receive=false){const items=proformaRows(p.proforma_items);return '<div class="table-wrap"><table class="table"><tr><th>Producto</th><th>Solicitado</th><th>Precio</th>'+ (receive?'<th>Recibido</th>':'<th>Subtotal</th>')+'</tr>'+items.map(i=>'<tr><td>'+esc(i.name)+'</td><td>'+i.quantity+'</td><td>'+moneySafe(i.unit_price)+'</td>'+(receive?'<td><input class="receipt-qty" data-product="'+i.product_id+'" data-requested="'+i.quantity+'" type="number" min="0" value="'+i.quantity+'"></td>':'<td>'+moneySafe(i.subtotal)+'</td>')+'</tr>').join('')+'</table></div>'}
  function proformas(){if(isSupplier())return supplierView();if(isBranch())return branchView();return '<div class="card"><p class="empty">No tienes permiso para ver facturas proforma.</p></div>'}
  function supplierView(){const list=(state.proformas||[]);return '<div class="card"><div class="card-head"><div><h3>Nueva factura proforma</h3><p class="muted">Documento de control sin movimiento de inventario.</p></div><button id="printProforma" class="link">Imprimir seleccionada</button></div><form id="proformaForm"><label>Sede destinataria<select id="proformaBranch"><option value="lisboa">BD Lisboa</option><option value="barrio">BD Barrio</option></select></label><div class="product-grid">'+state.products.map(p=>'<article class="product-card"><div class="product-name">'+esc(p.name)+'</div><div class="product-price">'+moneySafe(p.cost)+'</div><label>Cantidad<input class="proforma-qty" data-id="'+p.id+'" type="number" min="0" value="0"></label></article>').join('')+'</div><label>Notas<textarea id="proformaNotes" rows="2"></textarea></label><button class="primary">Enviar factura proforma</button></form></div><div class="card" style="margin-top:18px"><div class="card-head"><h3>Facturas proforma</h3><span class="muted">'+list.length+' registros</span></div>'+(list.length?'<div class="table-wrap"><table class="table"><tr><th>Número</th><th>Sede</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr>'+list.map(p=>'<tr><td>'+esc(p.invoice_number)+'</td><td>'+branchLabel(p.branch)+'</td><td>'+String(p.created_at).slice(0,10)+'</td><td><span class="pill">'+(statusLabel[p.status]||p.status)+'</span></td><td><button class="link proforma-print" data-id="'+p.id+'">PDF / imprimir</button>'+(!['cancelled','confirmed'].includes(p.status)?' <button class="link proforma-cancel" data-id="'+p.id+'">Cancelar</button>':'')+'</td></tr>'+ '<tr><td colspan="5">'+proformaTable(p)+'</td></tr>').join('')+'</table></div>':'<div class="empty">No hay facturas proforma.</div>')+'</div>'}
  function branchView(){const mine=(state.proformas||[]).filter(p=>branches().includes(p.branch)&&p.status!=='cancelled');return '<div class="card"><div class="card-head"><h3>Facturas recibidas</h3><span class="muted">'+mine.length+' pendientes</span></div>'+(mine.length?mine.map(p=>'<article class="proforma-receive card"><div class="card-head"><div><h3>'+esc(p.invoice_number)+'</h3><p class="muted">'+branchLabel(p.branch)+' · '+String(p.created_at).slice(0,10)+'</p></div><button class="link proforma-print" data-id="'+p.id+'">PDF / imprimir</button></div>'+proformaTable(p,true)+'<label>Observaciones<textarea class="receipt-notes" data-id="'+p.id+'" rows="2"></textarea></label><button class="primary receive-proforma" data-id="'+p.id+'">Guardar recepción</button></article>').join(''):'<div class="empty">No hay facturas recibidas.</div>')+'</div>'}
  function settings(){const saved=JSON.parse(localStorage.getItem('bdp-printer')||'null');return '<div class="card"><h3>Configuración de impresión</h3><p class="muted">En móvil, el sistema abrirá las opciones de compartir, guardar PDF o imprimir mediante la impresora configurada.</p><form id="printerForm"><label>Nombre de impresora<input id="printerName" value="'+esc(saved?.name||'')+'" placeholder="Ej. Impresora Bluetooth"></label><label>Tipo<select id="printerType"><option value="bluetooth">Bluetooth</option><option value="system">Impresora del sistema</option><option value="network">Red</option></select></label><button class="primary">Guardar como favorita</button></form>'+(saved?'<p class="pill">Favorita: '+esc(saved.name)+'</p>':'<p class="muted">No hay impresora favorita guardada.</p>')+'</div>'}
  function print(p){const items=proformaRows(p.proforma_items);const w=window.open('','_blank','width=800,height=900');if(!w)return;w.document.write('<!doctype html><html lang="es"><head><meta charset="utf-8"><title>'+esc(p.invoice_number)+'</title><style>body{font-family:Arial;padding:32px;color:#173c32}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{text-align:right;font-size:20px;margin-top:20px}</style></head><body><h1>BDPedidos</h1><h2>Factura proforma '+esc(p.invoice_number)+'</h2><p>Sede: '+branchLabel(p.branch)+'<br>Fecha: '+String(p.created_at).slice(0,10)+'</p><table><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr>'+items.map(i=>'<tr><td>'+esc(i.name)+'</td><td>'+i.quantity+'</td><td>'+moneySafe(i.unit_price)+'</td><td>'+moneySafe(i.subtotal)+'</td></tr>').join('')+'</table><div class="total">Total: '+moneySafe(items.reduce((a,i)=>a+i.subtotal,0))+'</div><p>'+esc(p.notes||'')+'</p></body></html>');w.document.close();w.focus();w.print()}
  const baseRender=render;render=view=>{if(view==='proformas'){document.getElementById('viewTitle').textContent='Facturas proforma';document.getElementById('content').innerHTML=proformas();bindProformas();return}if(view==='settings'){document.getElementById('viewTitle').textContent='Configuración';document.getElementById('content').innerHTML=settings();bindSettings();return}baseRender(view)};
  function bindProformas(){document.querySelectorAll('.proforma-print').forEach(b=>b.onclick=()=>{const p=state.proformas.find(x=>String(x.id)===b.dataset.id);if(p)print(p)});document.querySelectorAll('.proforma-cancel').forEach(b=>b.onclick=async()=>{if(!confirm('¿Cancelar esta factura proforma?'))return;await api('proforma_invoices?id=eq.'+b.dataset.id,{method:'PATCH',body:JSON.stringify({status:'cancelled',cancelled_at:new Date().toISOString(),cancelled_by:state.user.user.id})});await loadProformas();render('proformas')});const form=document.getElementById('proformaForm');if(form)form.onsubmit=async e=>{e.preventDefault();const rows=[...document.querySelectorAll('.proforma-qty')].map(i=>({product_id:Number(i.dataset.id),quantity:Number(i.value)||0,unit_price:Number(productById(i.dataset.id)?.cost)||0})).filter(x=>x.quantity>0);if(!rows.length)return alert('Agrega al menos un producto.');try{const p=(await api('proforma_invoices',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({supplier_id:state.user.user.id,branch:document.getElementById('proformaBranch').value,notes:document.getElementById('proformaNotes').value,status:'pending'})}))[0];await api('proforma_items',{method:'POST',body:JSON.stringify(rows.map(x=>({...x,proforma_id:p.id})))});await loadProformas();render('proformas')}catch(err){alert('No se pudo guardar la factura proforma.')}};document.querySelectorAll('.receive-proforma').forEach(b=>b.onclick=async()=>{const p=state.proformas.find(x=>String(x.id)===b.dataset.id),inputs=[...document.querySelectorAll('.receipt-qty[data-product]')];const rows=inputs.map(i=>({product_id:Number(i.dataset.product),requested_quantity:Number(i.dataset.requested)||0,received_quantity:Number(i.value)||0,unit_price:Number(productById(i.dataset.product)?.cost)||0,is_extra:false}));try{const receipt=(await api('proforma_receipts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({proforma_id:p.id,branch:p.branch,received_by:state.user.user.id,status:rows.every(x=>x.received_quantity===x.requested_quantity)?'confirmed':'partial',notes:document.querySelector('.receipt-notes[data-id="'+p.id+'"]')?.value||''})}))[0];await api('proforma_receipt_items',{method:'POST',body:JSON.stringify(rows.map(x=>({...x,receipt_id:receipt.id})))});await api('proforma_invoices?id=eq.'+p.id,{method:'PATCH',body:JSON.stringify({status:receipt.status})});await loadProformas();render('proformas')}catch(err){alert('No se pudo guardar la recepción.')}})}
  function bindSettings(){const f=document.getElementById('printerForm');if(f)f.onsubmit=e=>{e.preventDefault();localStorage.setItem('bdp-printer',JSON.stringify({name:document.getElementById('printerName').value.trim(),type:document.getElementById('printerType').value}));render('settings')}}
  function addNav(){const nav=document.querySelector('aside nav');if(!nav||document.querySelector('.proforma-nav'))return;const catalog=nav.querySelector('[data-view="catalog"]');if(isSupplier()||isBranch()){const b=document.createElement('button');b.className='nav-item proforma-nav';b.dataset.view='proformas';b.textContent='▣ Facturas proforma';b.onclick=()=>render('proformas');catalog?.after(b)}const s=document.createElement('button');s.className='nav-item settings-nav';s.dataset.view='settings';s.textContent='⚙ Configuración';s.onclick=()=>render('settings');nav.append(s)}
  const oldShow=showUser;showUser=()=>{oldShow();addNav()};
})();

